# Generated by Django 3.1.6 on 2021-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210207_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('complete', 'complete'), ('ongoing', 'ongoing')], default='ongoing', max_length=50),
        ),
    ]
